### ISSUE TITLE
Release of @nil-/doc 1.0

### ISSUE THREAD

**Issue by njaldea** [njaldea/mono#85]
TODO before API lock:
 - [ ] check if addition of non-fixed tuple/object prop type is possible
 - [ ] check viability of using a css framework
 - [x] #107
 - [x] improvements on event control
 - [x] improve title handling for user provided content (height)
 - [x] remove @nil-/doc logo in the title bar
 - [x] better library export (avoid one massive index file, for tree shaking)
 - [x] #108
 - [x] open and expand navigation page
 - [x] evaluate navigation icon to indicate if an item has a page equivalent
 - [x] add indicator to "collapse" navigation panel
 - [x] update svelte-package (and other dependencies)
 - [x] #106
 - [x] #117
 - [ ] ...

TODO if time allows:
- [x] override theme icon/toggle

**Comment by njaldea** [comment]
navigation page tasks is solved by the following:
- open/expand
  - done by exporting offset
  - sveltekit layer provides a store that keeps caches the offset value to localStorage
- navigation icon to indicate if an item has page
  - due to the layout of the navigation page, adding an icon feels off.
  - instead, the color of the background when hovered is more saturated when an item has a page equivalent
- indicator to collapse a navigation panel
  - maybe to be tackled in the future
  - where to place it is the main issue why i don't want to tackle it now

**Comment by njaldea** [comment]
improvements on event control
- currently, the solution is to simply stringify the detail of the event
- this will be tackled later post 1.0

**Comment by QuicheSama** [comment]
A suggestion for the `Color` control - allow the user to manually enter the hex value as text. I feel it would improve the ergonomics of using it :)

**Comment by njaldea** [comment]
> Could a `button` control be added to trigger an event?

events are internally triggered by the content (not by external trigger)
for example, if you have a `<button/>` for a "content", the way you trigger "click" event is by clicking the button.
